# Generated by Django 5.2 on 2025-06-29 17:12
from typing import (
    ClassVar,
)

import django.db.models.deletion
from django.conf import (
    settings,
)
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата начала забега')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                (
                    'athlete',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='runs',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Атлет',
                    ),
                ),
            ],
        ),
    ]
