# Generated by Django 5.2 on 2025-06-29 17:35
from typing import (
    ClassVar,
)

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ('apps_run', '0001_initial'),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name='run',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
