# Generated by Django 5.2 on 2025-07-01 06:39

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('apps_run', '0002_alter_run_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(
                choices=[('init', 'Init'), ('in_progress', 'In Progress'), ('finished', 'Finished')],
                default='init',
                max_length=20,
                verbose_name='Статус забега',
            ),
        ),
    ]
