# Generated by Django 5.2 on 2025-07-01 20:55

import django.core.validators
import django.db.models.deletion
from django.conf import (
    settings,
)
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('apps_run', '0003_run_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.TextField(verbose_name='Цели атлета')),
                (
                    'weight',
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(900),
                        ],
                        verbose_name='Вес атлета',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='athlete_info',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Атлет',
                    ),
                ),
            ],
        ),
    ]
