# Generated by Django 5.2 on 2025-07-04 18:21

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('apps_run', '0007_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.FloatField(null=True, verbose_name='Дистанция забега'),
        ),
    ]
