# Generated by Django 5.2 on 2025-07-06 08:14

import django.core.validators
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('apps_run', '0008_run_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectibleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('uid', models.CharField(max_length=100, verbose_name='Идентификатор предмета')),
                (
                    'latitude',
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                        verbose_name='Широта',
                    ),
                ),
                (
                    'longitude',
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                        verbose_name='Долгота',
                    ),
                ),
                ('value', models.IntegerField()),
                ('picture', models.URLField(verbose_name='Ссылка на картинку')),
            ],
        ),
    ]
