# Generated by Django 5.2 on 2025-07-06 12:29

from django.conf import (
    settings,
)
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('apps_run', '0009_collectibleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='athlete',
            field=models.ManyToManyField(related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Атлет'),
        ),
    ]
