# Generated by Django 5.2 on 2025-07-08 16:33

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('apps_run', '0010_collectibleitem_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(null=True, verbose_name='Общее время забега в секундах'),
        ),
    ]
