# Generated by Django 5.2 on 2025-07-09 05:02

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('apps_run', '0011_position_date_time_run_run_time_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общее время забега в секундах'),
        ),
    ]
