# Generated by Django 5.2 on 2025-07-10 15:17

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('apps_run', '0012_alter_run_run_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Расстояние с учетом предыдущих позиций'),
        ),
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(
                blank=True, null=True, verbose_name='Скорость в м/с относительно предыдущей позиции'
            ),
        ),
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Средняя скорость всех позиций'),
        ),
    ]
