# Generated by Django 5.2 on 2025-07-12 05:37

import django.db.models.deletion
from django.conf import (
    settings,
)
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('apps_run', '0013_position_distance_position_speed_run_speed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'athlete',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscriptions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Атлет',
                    ),
                ),
                (
                    'coach',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscribers',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Тренер',
                    ),
                ),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('athlete', 'coach'), name='unique_athlete_coach')],
            },
        ),
    ]
