# Generated by Django 5.2 on 2025-07-12 11:44

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('apps_run', '0014_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='full_name',
            field=models.CharField(
                choices=[
                    ('Пробеги 50 километров!', 'Distance'),
                    ('Сделай 10 Забегов!', 'Count'),
                    ('2 километра за 10 минут!', 'Speed'),
                ],
                max_length=100,
                verbose_name='Название челленджа',
            ),
        ),
    ]
